apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: reddit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: reddit-app
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-service
  namespace: reddit-app
spec:
  selector:
    app: reddit-clone
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
