# ec2_launch.yml
---
- name: Launch EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    aws_region: "us-east-2"
  tasks:
    - name: Launch 3 EC2 instances
      amazon.aws.ec2_instance:
        name: "my_instance"
        key_name: "ubuntu"
        instance_type: "t2.micro"
        image_id: "ami-04a81a99f5ec58529"     # Replace with your desired AMI ID
        count: 3
        region: "{{ aws_region }}"
        security_group: "default" # Replace with your security group ID
        wait: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Output instance information
      debug:
        msg: "Instance {{ item.id }} launched in {{ item.region }}"
      loop: "{{ ec2.instances }}"
