# ec2_launch.yml
---
- name: Launch EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    aws_region: "us-east-2"
    key_file_path: "/Users/tridibbasumatary/downloads/ubuntu1.pem"
  tasks:
    - name: Launch 3 EC2 instances
      amazon.aws.ec2_instance:
        name: "my_instance"
        key_name: "ubuntu1"
        instance_type: "t2.micro"
        image_id: "ami-0862be96e41dcbf74"  #our desired AMI ID
        count: 3
        region: "{{ aws_region }}"
        security_group: "default" # Replace with your security group ID
        wait: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Output instance information
      debug:
        msg: "Instance {{ item.instance_id }} launched"
      loop: "{{ ec2.instances }}"


    - name: Add new instances to inventory
      add_host:
          name: "{{ item.public_ip }}"
          ansible_user: "my_instance" # Adjust based on the AMI used
          ansible_ssh_private_key_file: "{{ key_file_path }}"
          loop: "{{ ec2.instances }}"
