apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-reddit-app
  namespace: reddit-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: domain.com
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: reddit-clone-service
            port:
              number: 3000
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-app
            port:
              number: 80
