---
- name: Install k3s and set up NGINX ingress controller using Helm
  hosts: localhost
  become: yes

  tasks:
    - name: Install k3s without Traefik
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | sh -s - --disable=traefik
      register: k3s_installation

    # - name: Wait for k3s service to be active
    #   ansible.builtin.shell:
    #     cmd: |
    #       until systemctl is-active --quiet k3s; do
    #         echo "Waiting for k3s to be active..."
    #         sleep 10
    #       done

    # - name: Wait for Kubernetes API to be ready
    #   ansible.builtin.shell:
    #     cmd: |
    #       until kubectl get nodes; do
    #         echo "Waiting for Kubernetes API..."
    #         sleep 15
    #       done
    #   register: api_status

    # - name: Install Helm
    #   ansible.builtin.shell:
    #     cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # - name: Add NGINX Ingress Helm repo
    #   ansible.builtin.shell:
    #     cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    # - name: Update Helm repos
    #   ansible.builtin.shell:
    #     cmd: helm repo update

    # - name: Install NGINX ingress controller via Helm
    #   ansible.builtin.shell:
    #     cmd: helm install nginx-ingress ingress-nginx/ingress-nginx
    #   register: nginx_installation

    - name: Check NGINX ingress installation
      ansible.builtin.debug:
        msg: "NGINX ingress installation {{ k3s_installation.stdout }}"
