# .github/workflows/launch_ec2_instances.yml
name: Launch EC2 Instances

on:
  workflow_dispatch

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto boto3

    - name: Run Ansible Playbook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ansible-playbook ec2_launch.yml
