name: Deploy K3s with NGINX Ingress

on:
  workflow_dispatch 

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # - name: Install Ansible
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install ansible

      # - name: Run Ansible Playbook
      #   run: ansible-playbook k3_install.yml

      - name: Set up kubectl
        run: |
          # mkdir -p $HOME/.kube
          # sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          # sudo chown $USER:$USER $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl create ns reddit-app
          kubectl get nodes -n reddit-app

      # - name: Configure Ingress controller
      #   run: |
      #     export KUBECONFIG=$HOME/.kube/config
      #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      #     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      #     helm repo update
      #     helm install nginx-ingress ingress-nginx/ingress-nginx

      # - name: Wait for NGINX Ingress controller to be ready
      #   run: |
      #     export KUBECONFIG=$HOME/.kube/config
      #     echo "Waiting for NGINX Ingress controller to be ready..."
      #     kubectl wait --namespace default \
      #       --for=condition=ready pod \
      #       --selector=app.kubernetes.io/component=controller \
      #       --timeout=300s

      - name: Run kubernetes commands 
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f deployment.yml 
          kubectl apply -f ingress.yml 
          kubectl get all -o wide -n reddit-app
          kubectl get ingress -n reddit-app -o wide
          kubectl get svc -n reddit-app -o wide
