name: Deploy K3s with NGINX Ingress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook k3_install.yml

      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          sudo chown $USER:$USER $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl create ns reddit-app
          kubectl get nodes -n reddit-app

      - name: Configure Ingress controller
        run: |
          export KUBECONFIG=$HOME/.kube/config
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install nginx-ingress ingress-nginx/ingress-nginx
          sleep 5
          

      # - name: Set up SSH to EC2
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Run Ansible Playbook
      #   run: |
      #     # ansible-playbook k3_install.yml
      #     ansible-playbook -i "localhost," -c local k3_install.yml


      - name: Run kubernates command 
        run: |

          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f deployment.yml 
          kubectl apply -f ingress.yml 
          kubectl get all -o wide -n reddit-app
          kubectl get ingress -n reddit-app -o wide
          kubectl get svc -o wide 

          
