name: Deploy k3s and NGINX Ingress

on:
  workflow_dispatch 
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --user boto boto3

      # - name: Set up SSH to EC2
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook k3_install.yml


      - name: Run kubernates command 
        run: |
          kubectl apply -f deployment.yml 
          kubectl apply -f ingress.yml 
          kubectl get all -o wide 

          
