name: Triggered by Repository Dispatch

on:
  repository_dispatch:
    types: [ custom-event ]

jobs:
  handle_dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Custom Script
        run: echo "This workflow was triggered by a repository_dispatch event with type"
