name: Test with the flow
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: action@checkout@v4
        
      - name: Hello world
        run: echo "hello world"
    
    
    
